### ISSUE TITLE
Edge Chromium support

### ISSUE THREAD

**Issue by ITMicaH** [nhtua/greencam#11]
I tried running this in Edge Chromium and it does run. But the video is very choppy and as soon as it opens my laptop's fans start blowing pretty hard.

Any chance on support for this browser?

**Comment by nhtua** [comment]
The online app now is in Pre-v1.0.0 support to modify the configuration. But it will not give you a good result. I would not recommend running this app on a laptop. You might want to get a real green cloth instead.

**Comment by LoSunny** [comment]
Totally agree, currently greencam relies on TensorFlow, which is resource-heavy. FYI, I only get like 5 FPS on my MacBook Air 2015 even with the lowest settings, but my CPU & GPU are already hitting 100 degrees. Moreover, by using a browser, your operating system will try to enable 3D acceleration, which is already much better than the NodeJS version I tried before (1 FPS). I hope someone will be able to provide some kind of server-processing that can improve the quality of video chatting on low powered systems.
