### ISSUE TITLE
Customize BodyPix Params

### ISSUE THREAD

**Issue by clee-ai** [nhtua/greencam#8]
Hey, really awesome project!

It'd be neat if there was an interface on the website to allow users to customize the parameters passed into `bodyPix.load`, so that they can use a better/worse model depending on what they need. And it'd allow them to mess around with settings to find one that works best.

If you think it's a good idea, I can take a look at making a PR.

**Comment by nhtua** [comment]
yay, Love to hear your voice. I had the same vision. My original idea was:
- index.html - Editor with text input, slider to custom value
- player.html - Editor submits those values to player.html and puts it into the URL query, somehow like `/player.html?model=MobileNetV1&multiplier=0.75`
- player.html uses params from URL to run bodyPix.load

But I couldn't manage time to implement a HTML UI for it. Looking forward for new concept/design.

**Comment by clee-ai** [comment]
I think something like this would be useful. Maybe I can adapt this page and then have it spit out a URL with parameters to input into OBS. https://flect-lab-web.s3-us-west-2.amazonaws.com/P01_wokers/t01_bodypix/index.html

One of most important hyperparameters for avoiding artifacts seems to be image size. I'll investigate how to tune it for best results given a webcam's input size.
